// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bklhtllisbmpfctcuwzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbGh0bGxpc2JtcGZjdGN1d3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNjI5MDAsImV4cCI6MjA3NzYzODkwMH0.cNejAoJIIh9U_Gg9Pg7ARllOCtm4MelQU1dbJEX3_AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});